MicroStrategyMappings:
  ObjectTypes:
    - source: "MicroStrategyReport" # MSTR Grid/Graph Report
      target: "PowerBIPage"
      notes: "Often maps to a single page with a table/matrix or simple visual."
    - source: "MicroStrategyDocument"
      target: ["PowerBIReport", "PowerBIPaginatedReport"]
      notes: "Complex. Might be split into multiple PBI Report pages or rebuilt as Paginated Report for pixel-perfection."
    - source: "MicroStrategyDossier"
      target: "PowerBIReport"
      notes: "Best fit for Power BI interactive reports."
    - source: "MicroStrategyMetric"
      target: "PowerBIMeasure"
    - source: "MicroStrategyAttribute"
      target: "PowerBIColumn" # (in a dimension table)
    - source: "MicroStrategyFact"
      target: "PowerBIColumn" # (in a fact table, to be aggregated by measures)
    - source: "MicroStrategyPrompt"
      target: "PowerBISlicer" # or PowerBIParameter
    - source: "MicroStrategyIntelligentCube"
      target: "PowerBIDataset_ImportMode"

  VisualTypes: # From MSTR Reports/Documents/Dossiers
    - source: "Grid"
      target: ["MatrixVisual", "TableVisual"]
    - source: "Graph:VerticalBar:Clustered"
      target: "ClusteredBarChart"
    # ... many more visual mappings ...

  FunctionMappings: # For your Formula Conversion Service (can be in a separate file too)
    - source_function_name: "Sum" # MSTR Sum
      target_function_name: "SUM"  # DAX SUM
      # Potentially add context for level metrics, conditions, transformations
    - source_function_name: "Avg"
      target_function_name: "AVERAGE"
    - source_function_name: "ApplySimple"
      target_function_name: "N/A - Manual Review Required"
      confidence: "Low"
      notes: "Embeds SQL. Requires complex parsing or manual rewrite in DAX or Power Query."
    # ... other MSTR functions like RunningSum, OLAPSum, Rank, etc.

  # Field mappings will be more about extracting structured info from MSTR object definitions
  # Example for extracting a metric definition using REST API JSON response
  MetricDefinition:
    source_api_path: "/metrics/{metricId}/definition" # Example endpoint
    field_mappings:
      name:
        source_json_path: "name"
      expression:
        source_json_path: "expression.text" # Or "expression.tree" if structured
      description:
        source_json_path: "description"
        default: ""
      folder_path:
        source_json_path: "ancestors[*].name" # Join to form path
